### ISSUE TITLE
Prepared Containerfile

### ISSUE THREAD

**Issue by matfechner** [osism/container-image-tang#1]
Hi @berendt,

i've prepared the Tang Containerfile
please take  a look here https://github.com/matfechner/container-image-tang

**Comment by berendt** [comment]
@matfechner LGTM. Can you prepare a PR for this repository? I will create the required Quay repository + add the secrets to this repository.

**Comment by matfechner** [comment]
Hi @berendt,

thanks,
please open an initial commit for this repository, then i will create a PR

**Comment by berendt** [comment]
@matfechner Done.

**Comment by matfechner** [comment]
after merge it is done
